version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - NET1
  backend:
    container_name: backend
    build:
      context: ./backend
      target: development
    env_file:
      - ./backend/.env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - postgres
    networks:
      - NET1
    command: run.sh
    volumes:
      - ./backend:/app
      - /app/node_modules
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - NET1
volumes:
    db_data:

networks:
  NET1:
    driver: bridge