version: '3.8'
services:
  test-db:
    image: postgres:13
    container_name: postgres_test
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5434:5432
    networks:
      - NET1
  dev-db:
    image: postgres:13
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - NET1
  # backend:
  #   build:
  #     context: ./backend
  #     # target: development
  #   ports:
  #     - 3000:3003
  #   depends_on:
  #     - postgres
  #   links:
  #     - postgres
  #   networks:
  #     - NET1
  #   # command: init_script.sh
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  # jenkins:
  #   image: jenkins/jenkins:lts
  #   ports:
  #     - "8080:8080"
  #     - "50000:50000"
  #   volumes:
  #     - jenkins_home:/var/jenkins_home
  # adminer:
  #   image: adminer
  #   container_name: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - NET1
volumes:
  # jenkins_home:
    db_data:

networks:
  NET1:
    driver: bridge