version: "3.8"
services:
  postgres:
    image: postgres:13
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - NET1
  backend:
    container_name: backend
    build:
      context: ./backend
      target: development
    ports:
      - "127.0.0.1:${BACKEND_PORT}:${BACKEND_PORT}"
      - "127.0.0.1:5555:5555" #for prisma Database Management
    depends_on:
      - postgres
    networks:
      - NET1
    volumes:
      - ./backend:/app
      - /app/node_modules
  client:
    container_name: client
    build:
      context: ./Client
      target: development
    ports:
      - "127.0.0.1:${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    networks:
      - NET1
    volumes:
      - ./Client:/app
      - /app/node_modules
volumes:
  db_data:
networks:
  NET1:
    driver: bridge
