name: Continuous Integration

# This action works with pull requests and pushes
on:
  pull_request:
    branches: [develop]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{ts,tsx}
          only_changed: True
